name: Build and Release ISO on Commit

on:
  push:
    branches:
      - '**' # Adjust to specific branches if needed

jobs:
  build-and-release:
    name: Build ISO and Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies (Debian-based)
      run: |
        sudo apt update
        sudo apt install -y build-essential nasm xorriso clang grub-common mtools qemu
        sudo apt install -y llvm clang gcc-multilib g++-multilib

    - name: Install Rust and Configure Toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup install nightly-x86_64-unknown-linux-gnu
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
        rustup override set nightly

    - name: Build ISO
      run: make

    - name: List Generated Files
      run: ls -lah

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload ISO to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./oreneta.iso # Replace with the actual path to the generated ISO
        asset_name: oreneta.iso # Replace with the desired file name
        asset_content_type: application/octet-stream
